main.go

Add "--reset-values" flag

---

diff/diff.go

I have mistakenly introduced a build error due to my merge mistake while resolving conflicts in #65. This fixes that.

fix: Follow-up for the detailed exit code feature

---

.circleci/config.yml

A step forward towards #56 
See https://circleci.com/gh/mumoshu/helm-diff/2 to verify the build is passing, and to see how it works.

ci: Start building on CircleCI

---

cmd/revision.go
cmd/rollback.go
cmd/upgrade.go

fix: Suppress unnecessary command usage when theres diff

---

cmd/helm.go
cmd/upgrade.go

add --set-file support

---

cmd/helm.go

Feat: Added an ability to pass values from stdin

---

cmd/upgrade.go

As discussed in https://github.com/databus23/helm-diff/pull/72#issuecomment-456730822 here's a new option to disable hooks while doing a `diff upgrade`.

Add option to disable hooks in diff upgrade

---

cmd/helm3.go
cmd/upgrade.go

fix issues in --reset-values and --reuse-values on helm v3

---

install-binary.sh

Follow-up for #224

---

install-binary.sh

fix: added macOS ARM M1 architecture support

---

Makefile

Add a binary build for apple m1 to makefile.

add-apple Add binary build for apple m1

---

cmd/upgrade.go

Set HELM_DIFF_IGNORE_UNKNOWN_FLAGS=true to ignore unknown flags on helm-diff-upgrade

---

cmd/helm3.go

Fix helm-diff-release

---

Makefile

Fix for the docker version used, should not be 1.7.5 but 1.17.5.

Fix golang docker version

---

cmd/upgrade.go

Make HELM_DIFF_THREE_WAY_MERGE log less verbose

---

cmd/upgrade.go
go.mod
go.sum
main.go

Add various client-go auth providers for 3-way merge

---

cmd/helm3.go

Fix HELM_DIFF_USE_UPGRADE_DRY_RUN to work for new installs

---

Makefile

add unittest cover

---

plugin.yaml

Once this gets merged, I will tag it and push, so that the release process starts.

Bump the plugin version to 3.9.3

---

cmd/helm3.go

Fixed a little typo in comments.

Fix Typo In Comments

---

.golangci.yaml
cmd/upgrade.go
go.mod
go.sum

Use module instead of incompatible version

deps: use json-patch/v5 instead of incompatible module

---

.golangci.yaml

[Testifylint](https://github.com/Antonboom/testifylint) help apply github.com/stretchr/testify best practices.
The list of linters has also been sorted for readability

enable testifylint linter

---

manifest/parse.go
manifest/parse_test.go
manifest/testdata/configmaplist_v1.yaml
manifest/testdata/secretlist_v1.yaml

https://github.com/databus23/helm-diff/issues/601

match all k8s list resources

---

plugin.yaml

fix: https://github.com/databus23/helm-diff/issues/688

Bump helm-diff version to 3.9.12
