README.md

Closes #2 
Using the plugin manager simplifies installation in Helm > 2.3.x

docs(install): Add helm plugin manager install procedure

---

main.go

Fixes #13 
Love the plugin - it's been incredibly helpful for making upgrades smooth.  I think it would be very convenient to be able to replace `diff` with `upgrade` from a previous shell command and rerun it.  That is one less way for me to make mistakes during the process.  I'd imagine you don't want to start a trend of copying all the options for `helm upgrade` into this plugin.  This one seems pretty crucial to me, but let me know what you think!
FWIW, I was not able to test this on Helm 2.7.  I'm currently running 2.6, so I checked out `v2.5.0+1` (`HEAD~1` at time of writing) and branched off that to build and test.  I then `cherry-pick`ed that commit into this branch.  So all that said it'd be great if you can either a) test this on 2.7 yourself or b) give me a few weeks to upgrade …

Support --reuse-values

---

diff.go
main.go
manifest/parse.go

Fixes #11 
- Allows easy suppression of secret content diff via the `-q` or `--suppress-secrets` flags 
- Allows additional customization of suppression via the `--suppress` flag

Enabling selecting filtering of diff output

---

helm.go

I've had the problem that helm-diff failed when I specified a remote Helm chart on the command line. Investigation showed that ChartDownloader failed because it knew nothing about the http and https schemes. This PR fixes this problem. I'm using Helm version 2.7.2.
* Call ChartDownloader with a list of all available getters
* Return error from downloadTo to get better feedback why
something went wrong

Fix access to remote Helm repostories

---

helm.go

Downloading remote chart to Archive dir (~/.helm/cache/archive) would keep the current dir clean.

Download remote chart to Archive dir

---

helm.go
main.go

Ensures that a value file actually exists instead of throwing up a golang exception when trying to open a file that doesn't exist

Ensure values files exist

---

cmd/revision.go
cmd/rollback.go
cmd/root.go
cmd/upgrade.go

This provides the ability to do a diff on revisions.
I have made some improvements with 
- safer code terminations with (exit 0),
- Intelligent suggestions for subcommands
- docs
- code restructuring.
kindly have a look, and let me know in case of corrections/bugs.
Thanks..!!

feature Implementation: Diff between Revisions #6

---

README.md
cmd/root.go
cmd/upgrade.go

Hi,
This PR follows #22 , which updates the usage docs and Readme
hope this can be merged asap

Readme and Usage Updation : following #22

---

install-binary.sh

This fixes a bug where the --version flag that can be passed to `helm
plugin install` was not working with the install-binary.sh script that
this repository uses to install the binary files for users.
The issue was that the Helm runs install hooks in the current working
directory [1], so the `git describe` command that this repository was
executing was not being executed in the directory of the plugin, and
would thus always fail. The fix here is to use the `-C` flag to git to
specify the directory of the plugin source, ensuring that it will work
correctly regardless of the working directory from which the script is
executed.
Closes https://github.com/databus23/helm-diff/issues/50
[1] https://github.com/kubernetes/helm/blob/401f8bcc187d7a9edeec12c26c64819f105954d5/cmd/helm/plugin.go#L48-L72 …

fix install-binary.sh version specification

---

cmd/upgrade.go
main.go

This provides the ability to do a `diff` on a release that does not currently exist.  This makes it much easier to use the plugin with things like `helmfile` as it doesn't error out and provides valuable feedback.  
NOTE: I have an additional PR that manages the merge conflicts of my two PRs that might be easier to merge for you.

New chart diffing

---

install-binary.sh
plugin.yaml

When installing plugin in debug mode helm home is also running in debug mode and returning wrong values.
This patch adds --debug=false flag to helm home

Turn off debug for helm home

---

README.md
cmd/revision.go
cmd/rollback.go
cmd/upgrade.go
diff/diff.go
diff/diff_test.go

By default disabled, can be enabled and configured with `--context NUM`.
Wdyt?
This is my first time writing Go code, please let me know if my naming is off, something should be refactored or just be done differently!
The code iterates over all diff records and keep track of how many lines are between the closest change (addition or removal) *before* the current line. Then it iterates again through all diff records but backwards and adjusts the *distance* if the closest change *after* the current line is closer.
When printing the diff we can then simply omit records that have a *distance* larger than the desired *context*.
I have an alternative implementation which first creates *chunks* and then iterates over chunks of diffs to print, if you prefer it: …

Allow to omit large common parts in diff output

---

cmd/revision.go
cmd/rollback.go
cmd/upgrade.go
manifest/parse.go

helm charts can deploy to multiple namespaces at once, so compare on
(namespace, name, kind, version) instead of just (name, kind, version).
(We're deploying ResourceQuotas with the same name across multiple namespaces)

add namespace to deduplication tuple

---

cmd/helpers.go
cmd/revision.go
cmd/rollback.go
cmd/upgrade.go

This pull request add support for connecting to a Tiller server secured with TLS.

feat: TLS-based client auth support

---

cmd/revision.go
cmd/rollback.go
cmd/upgrade.go
manifest/parse.go

Currently helm diff does not parse helm hooks. This appends hooks to the manifest diffs so that it can include them to be diff. Added capability to revision,upgrade and rollback.

feat: Capability to diff changes in chart hooks

---

diff/diff_test.go
glide.lock
glide.yaml
manifest/parse.go
manifest/parse_test.go
manifest/testdata/deploy_v1.yaml
manifest/testdata/deploy_v1beta1.yaml
manifest/testdata/pod.yaml
manifest/testdata/pod_namespace.yaml

Resolves #70
When the apiVersion of a Kind changes, helm-diff detects this as a
remove/readd of the whole manifest; this makes it difficult to see the
actual changes. This change enables a small heuristic so apiVersion
changes like `authentication.k8s.io/v1beta1` ->
`authentication.k8s.io/v1` show up as a one-line diff instead of a
full-manifest diff, while hopefully not meddling with unexpected
apiVersions too badly.

feat: Improved diff on apiVersion changes

---

Makefile
diff/diff.go
diff/diff_test.go

As the follow-up for recent merges. `make test` should be passing now.

chore: Test fixes and small tweaks

---

Makefile
cmd/error.go
cmd/revision.go
cmd/rollback.go
cmd/upgrade.go
diff/diff.go
main.go

This feature is enabled only when the `--detailed-exitcode` flag (#65) is provided.
Supports `upgrade`, `revision` and `rollback` sub-commands.
Resolves #54, but only after https://github.com/helm/helm/pull/4367 is released with helm v2.11.0, probably.

feat: Dedicated exit code (2) on there's diff

---

cmd/helm.go
cmd/upgrade.go

This resolves an issue where numeric values intended to be
used as strings could be interpreted as float64 values,
causing varius things to fail in unexpected ways.
This fix mirrors the changes in the following PR to Helm
itself: https://github.com/helm/helm/pull/3599
Closes https://github.com/databus23/helm-diff/issues/83

add --set-string flag to ensure proper parsing of strings

---

cmd/upgrade.go

feat: Add support for the non-default namespace for the targeted release

---

glide.lock
glide.yaml
plugin.yaml

Ran `glide update` and `glide install --strip-vendor`, followed by manual changes to `glide.lock` to revert `k8s.io/*` pkg versions to those seen in helm's glide.lock https://github.com/helm/helm/blob/cc7cc1087f586f64d0b0d08aa516a003ced2d85b/glide.lock#L457 to avoid build errors.
Resolves #81

Bump Helm to v2.10.0

---

Makefile
install-binary.sh

Enable `helm-diff` on `freebsd`
* No freebsd binary for releases
* Could not install plugin using `helm plugin install https://github.com/databus23/helm-diff --version master`
* Build freebsd binary for releases
* Should be able to use `helm plugin install https://github.com/databus23/helm-diff --version master` (will have to test once release of new version actually happens)
It currently works fine if built locally:
```
$ gmake build
mkdir -p bin/
go build -i -v -o bin/diff -ldflags="-X github.com/databus23/helm-diff/cmd.Version=2.10.0+2 -X github.com/databus23/helm-diff/vendor/k8s.io/helm/pkg/version.BuildMetadata= -X github.com/databus23/helm-diff/vendor/k8s.io/helm/pkg/version.Version="
$ bin/diff version
2.10.0+2
$ gmake dist
...
GOOS=freebsd GOARCH=amd64 go build -o …
```

Feat: build freebsd bin

---

cmd/helpers.go

To enable support for the TLS environment variables (HELM_TLS_ENABLE), I replace the old tls parse logic with the AddFlagsTLS method from Helm.

Use AddFlagsTLS from helm to add tls cmd options.

---

cmd/upgrade.go
manifest/parse.go

First pass adding option to disable test hooks specifically

---

cmd/revision.go
cmd/rollback.go

Apologies for breaking things. I was able to get my tests failing locally and they are now passing. I took a bit of an assumption on how you would like to go about this. If this is incorrect let me know and I will happily make changes ASAP.

Fixing tests that were broken with #119

---

manifest/parse.go
manifest/parse_test.go
manifest/testdata/empty.yaml

Fixes the variant of #48 reported by bfin, jcalahan and adidenko.
If you have templates that wind up containing only comments, they should be skipped.  This change checks to see if the metadata is completely empty to detect effectively blank yaml content.
To do this without an extraneous comparison variable, I had to unshadow the metadata type.  This resulted in a few extra cosmetic changes in the diff.

Skip yaml blocks without any metadata

---

README.md
cmd/release.go
cmd/root.go
diff/diff.go
glide.lock

Hi,
This PR resolves #130 and it contains the following changes
- add diff release subcommand to compare different releases
- update subcommand usage in README.md 
- adds go report card badge and license badge to the README.md 
suggestions and comments..?

feature: diffing between different releases

---

glide.lock

For somehow reason, current glide.lock pinned `mergo` to a very old
version (dates back to 2014), while github.com/Masterminds/sprig
referenced asked for ~v0.3.7 in their glide.yaml which caused build
failure.
This change bumps Mergo to v0.3.7 to satisfy the dependency requirement
Fixes #134
Signed-off-by: Qiu Yu <unicell@gmail.com>

Bump github.com/imdario/mergo reference to v0.3.7

---

install-binary.sh

```
gabdav01@e109198-mac:~/tmp
export HELM_HOME="/tmp/foo me"
gabdav01@e109198-mac:~/tmp
$ helm init --client-only
Creating /tmp/foo me
Creating /tmp/foo me/repository
Creating /tmp/foo me/repository/cache
Creating /tmp/foo me/repository/local
Creating /tmp/foo me/plugins
Creating /tmp/foo me/starters
Creating /tmp/foo me/cache/archive
Creating /tmp/foo me/repository/repositories.yaml
Adding stable repo with URL: https://kubernetes-charts.storage.googleapis.com
Adding local repo with URL: http://127.0.0.1:8879/charts
$HELM_HOME has been configured at /tmp/foo me.
Not installing Tiller due to 'client-only' flag having been set
Happy Helming!
gabdav01@e109198-mac:~/tmp
$ helm plugin install https://github.com/databus23/helm-diff
sh: /tmp/foo: No such file or directory
Error: plugin install …
```

Fix install when HELM_PATH contains a space

---

manifest/parse.go

The scanner has a fixed buffer size of 1MB. If this is exceeded scanning will fail silently, leading to misleading diff output.
This helps improve the failure mode for #139.

Fix: Check for errors after scanner.Scan()

---

Makefile
README.md
cmd/error.go
cmd/helm.go
cmd/helpers.go
cmd/release.go
cmd/revision.go
cmd/rollback.go
cmd/root.go
cmd/upgrade.go
diff/diff.go
diff/diff_test.go
manifest/parse.go
manifest/parse_test.go
scripts/update-gofmt.sh
scripts/verify-gofmt.sh
scripts/verify-golint.sh
scripts/verify-govet.sh

This PR,
- Refactors code using `gofmt` and `go lint` to improve code quality. 
- Adds scripts to `gofmt` code and to update required changes
- Adds scripts to `go lint` and `go vet` code
- Adds `lint` stage before `build` to retain code quality
- Adds Godocs Badge to README.md
**preview**:
goes from [![Go Report Card](https://goreportcard.com/badge/github.com/databus23/helm-diff)](https://goreportcard.com/report/github.com/databus23/helm-diff) to [![Go Report Card](https://goreportcard.com/badge/github.com/aananthraj/helm-diff)](https://goreportcard.com/report/github.com/aananthraj/helm-diff)

Improve code quality using gofmt and go lint

---

cmd/helm3.go
cmd/helpers.go
cmd/release.go
cmd/revision.go
cmd/rollback.go
cmd/upgrade.go
manifest/parse.go
manifest/parse_test.go
manifest/testdata/pod_hook.yaml

Here is an other version for #147 which shells out to `HELM_BIN`.
The following helm commands are used:
- `helm template` for update
- `helm get` to retrieve releases and revisions
The following flags are not supported in helm 3 mode:
- `--set-file` in `upgrade`
- `--no-hooks` in `upgrade` (`helm template` in v3.0.0-beta.3 ignores this flag and returns always no hooks)
- `--include-tests` in all commands as we ignore all hooks
It would be possible to get the hooks for the installed releases/revisions if it is really needed.

support helm 3 using exec

---

.circleci/config.yml
Makefile

Upgrade to golang v1.13.3 (anchor the patch version)

golang v1.13.3

---

install-binary.sh

Disabling grep colouring mode directly for the execution, because it causes issues when accessing the url with curl if `GREP_COLOR` is set to `always`.
As you can see below, curl will use invalid url set by `getDownloadURL` function. The issue is in line 76 of the install/update script where the OS name is grepped. (https://github.com/databus23/helm-diff/blob/master/install-binary.sh#L76)
If colouring mode is disabled for grep, it will not include the terminal colouring chars in the download url and the new release can be downloaded.
```
curl: (3) bad range in URL position 82: https://github.com/databus23/helm-diff/releases/download/v3.0.0-rc.7/helm-diff-\u001b[01;31m\u001b[Kmacos\u001b[m\u001b[K.tgz
```
```
TASK [helm_diff : Update helm diff plugin] …
```

Disabling grep colouring mode directly for the execution

---

manifest/parse.go

Fix #182 
We are experiencing this issue while updating the dashboard JSON contents of [Grafana](https://github.com/helm/charts/tree/master/stable/grafana) chart, which leads to a huge length of the YAML specs.

Increase the size of bufio.Scanner.Buffer to 10MiB.

---

cmd/release.go
cmd/revision.go
cmd/rollback.go

The rollback, release and revision command has the code for using detailed exit code but the flags are not there. So I added the flags.

Added detailed exitcode flag to revision, release and rollback

---

README.md
cmd/helm3.go
cmd/upgrade.go

Feat: Expose post-renderer flag in the upgrade subcommand

---

cmd/helm3.go
cmd/upgrade.go
plugin.yaml

Added disable-openapi-validation helm3 flag support to disable rendered templates validation with the Kubernetes OpenAPI Schema.
https://github.com/helm/helm/pull/7570
It fixes https://github.com/databus23/helm-diff/issues/209

Add support for Helm 3 --disable-openapi-validation flag

---

cmd/upgrade.go

This behaves exactly the same as 'helm diff upgrade --allow-unreleased',
but it matches the same arguments as helm itself, so that check scripts
and deployment scripts can be basically the same, e.g.
check:
helm diff upgrade --install myapp ./myapp
install:
helm upgrade --install myapp ./myapp
and this'll work regardless of whether the release exists or not.
Ref https://github.com/databus23/helm-diff/issues/108

Added support for 'helm diff upgrade --install'

---

cmd/upgrade.go

re: #197 
Accept and ignore top-level `--kubeconfig` flag, to allow for usage with microk8s.

Allow passing --kubeconfig flag to diff plugin

---

install-binary.sh

Ensure POSIX compatibility
Fixes #204

Change to use sh instead of bash

---

install-binary.sh

Fix regression on plugin installation for Helm 2

---

Makefile
cmd/upgrade.go
diff/constant.go
diff/diff_test.go
diff/report.go

This adds the JSON output on top of #221, which can be enabled by passing `--output json`. Internally it works exactly the same as the `template` output format with the default template.
```
********************
Release was not present in Helm.  Diff will show entire contents as new.
********************
[{
"api": "v1",
"kind": "Secret",
"namespace": "default",
"name": "mysql-1567775891",
"change": "ADD"
},{
"api": "v1",
"kind": "ConfigMap",
"namespace": "default",
"name": "mysql-1567775891-test",
"change": "ADD"
},{
"api": "v1",
"kind": "PersistentVolumeClaim",
"namespace": "default",
"name": "mysql-1567775891",
"change": "ADD"
},{
"api": "v1",
"kind": "Service",
"namespace": "default",
"name": "mysql-1567775891",
"change": "ADD"
},{
"api": "apps",
"kind": "Deployment",
"namespace": …
```

feat: JSON output

---

cmd/helm3.go
cmd/upgrade.go

`--disable-openapi-validation` seems to not work against charts like prometheus-operator because it results in "missing kind" errors due to that it tries to install CRD and CR on first install. That is different than OpenAPI schema validation, which seems rather for detecting invalid fields.
The addition of `--disable-validation` disables the manifests validation against the targeted K8s cluster(again, since Helm 3 `helm template --validate` runs validation against the live cluster so it is relevant), so that we can make use of helm-diff even for cases `--disable-openapi-validation` doesn not work.
Resolves #183

Add --disable-validation for disabling validation against K8s cluster entirely

---

cmd/helm3.go
cmd/upgrade.go

I found this to be handy when you want to review what is being installed outside of your terminal, on e.g. your CI/CD pipeline, while hiding secrets 😃

Add `helm diff upgrade --dry-run` to show install diff without cluster access

---

cmd/helm3.go
cmd/upgrade.go
diff/diff.go

Depends on #230
`helm diff upgrade` output is non-determinisic, due to that it shows diff entry in the order of the Go map objects containing source/target maniefsts to be compared.
The non-determinism makes writing integration test with something and helm-diff harder, as snapshot testing is impossible.
This patch fixes it by enhancing the diff logic to sort those map keys in the alphabetical order and use the result for iterating map entries.
Note that you can use the below snippet for non-scientific testing to verify that the result is (seemingly) deterministic now:
```
for (( i=0; i<10; ++i)); do helm --debug diff upgrade --dry-run foo stable/prometheus-operator | sha256sum ; done
```
Before this change it should print output like:
```
$ for (( i=0; i<10; ++i)); do helm --debug diff …
```

Make diff result as deterministic as possible

---

manifest/parse.go
manifest/parse_test.go
manifest/testdata/list.yaml

Fixes #201
See https://github.com/databus23/helm-diff/issues/201#issuecomment-667750640 for how it works.

Fix `Found duplicate key "resource, , List (v1)"` errors

---

Makefile
README.md

- Added documentation to install from source (useful if no binaries are compatible)
- Added a dependency on the `build` target in the Makefile's `install/helm3` target to allow one-line installation
Ref #275

Added Source Installation Documentation

---

install-binary.sh

This fixes `install-binary.sh` to use correct helm binary

fix: correct helm binary in install script for environment that have both helm 2 and 3 installed

---

cmd/root.go
go.mod

In the absence of an explicit `--no-color` flag specification, try to infer whether the standard output is a terminal, and only emit colored output when it is.
This only affects invocations without the flag, all of `--no-color`, `--no-color=false`, and `--no-color=true` retain their original semantics.
See example:

Automatically color output based on whether output is a terminal

---

README.md
cmd/release.go
cmd/revision.go
cmd/rollback.go
cmd/upgrade.go
diff/diff.go
diff/diff_test.go

This PR add support to strip the trailing cr from charts that have been deployed wit different line endings.
See #144

add support for strip-trailing-cr

---

cmd/release.go
cmd/revision.go
cmd/rollback.go
cmd/upgrade.go
manifest/parse.go
manifest/parse_test.go

The current behavior of helm-diff is to show diffs even when the YAML files are semantically identical but they contain style
differences, such as indentation or key ordering.
As an example, the following two YAMLs
```yaml
apiVersion: v1
kind: Service
metadata:
name: app-name
labels:
app.kubernetes.io/name: app-name
app.kubernetes.io/managed-by: Helm
spec:
ports:
- name: http
port: 80
targetPort: http
selector:
app.kubernetes.io/name: app-name
type: ClusterIP
```
```yaml
apiVersion: v1
kind: Service
metadata:
labels:
app.kubernetes.io/managed-by: Helm
app.kubernetes.io/name: app-name
name: app-name
spec:
ports:
- name: http
port: 80
targetPort: http
selector:
app.kubernetes.io/name: app-name
type: ClusterIP
```
would be showing the following diffs
```diff
apiVersion: v1
kind: Service …
```

Normalize YAML manifests before running diff

---

diff/diff.go
install-binary.sh

The script failed because of some conditions assumed true, fixed as follow:
* if HELM_BIN is not set the just uses helm path
* helm home command doesn't seem to exist on helm3.x, using a default path if this is the case
* tgz downloaded file wasn't extracted properly
resolves #244

Fix for Install-Binary script

---

diff/diff.go
diff/report.go

the Manifests codepath was calling setupReportFormat on a mutable global map,
which means that calling Manifests from different gothreads is an error,
and can produce a panic with this (abbreviated) traceback:
```
fatal error: concurrent map writes
goroutine 668 [running]:
runtime.throw(0x27cb973, 0x15)
/usr/local/go/src/runtime/panic.go:1116 +0x72 fp=0xc003a8c710 sp=0xc003a8c6e0 pc=0x437892
runtime.mapassign_faststr(0x23fc3a0, 0xc019650120, 0x27a837d, 0x6, 0xc00012f408)
/usr/local/go/src/runtime/map_faststr.go:211 +0x3f1 fp=0xc003a8c778 sp=0xc003a8c710 pc=0x414811
github.com/databus23/helm-diff/v3/diff.setupDiffReport(...)
/go/pkg/mod/github.com/databus23/helm-diff/v3@v3.1.3/diff/report.go:99
github.com/databus23/helm-diff/v3/diff.(*Report).setupReportFormat(0x3dafe80, 0x27a5ada, 0x4) …
```

fix report concurrency crash when helm-diff used as a library

---

cmd/root.go

See how it works by running `helm-diff` with or without setting the `TERM` value:
```
HELM_NAMESPACE=default HELM_BIN=helm372 ./helm-diff upgrade envoy1 stable/envoy --three-way-merge
TERM=dumb HELM_NAMESPACE=default HELM_BIN=helm372 ./helm-diff upgrade envoy1 stable/envoy --three-way-merge
```
Fixes #281

Disable colors when TERM=dumb

---

README.md
cmd/helm3.go
cmd/upgrade.go

Add support for --api-versions in helm-diff-upgrade

---

README.md
cmd/helm3.go
cmd/upgrade.go

feat: HELM_DIFF_USE_UPGRADE_DRY_RUN

---

cmd/upgrade.go

Fix --three-way-merge to not show diff on meta.helm.sh annotations

---

Makefile

docker-run-release was still building using golang 1.13.3. Should use 1.17 to match the rest of the project.

Start using golang 1.17.5 to build release

---

README.md
cmd/upgrade.go

This adds a dedicated envvar to enable the three-way-merge diff added in #304. It should be useful when you are using helm-diff from another command or script and you dont have ability to specify the --three-way-merge flag without modifying the command/script but you cant due to various reasons.

HELM_DIFF_THREE_WAY_MERGE=true to imply --three-way-merge

---

install-binary.sh

See https://github.com/databus23/helm-diff/issues/322#issuecomment-1008660815.

Fix install script

---

README.md
cmd/root.go

--color or HELM_DIFF_COLOR=true to force color

---

cmd/helm3.go

Hi,
Unfortunately previous [PR](https://github.com/databus23/helm-diff/pull/272) was close as state, but this fix is still needed, so I've created a new one. Please review it once you have time. thanks!
There is an issue in helm-diff for helm3 version, it doesn't include values from stdin. For helm2 it works as expected.
```
$ cat values-10.yaml                                                               
lolkek:                                                                            
helloword: test                                                                  
new:                                                                             
ohoho:                                                                         
values-10: lolodddd10 
```
Current behavior:
``` …
```

helm-diff doesn't include values from stdin for helm3 version

---

.editorconfig
.github/workflows/ci.yaml
Makefile

Hi,
i recently read
> It would be great if anyone could enahnce our CI workflow to cover cygwin (if it's possible).
- https://github.com/databus23/helm-diff/pull/287#issuecomment-1008224018
and thought I can re-design the CI workflow in general in form as a proposal.
The new CI based on Github Action. It covers all tasks from Circle CI +
* helm plugin install on MacOS and Windows (3 variants)
* integration tests against real kubernetes
* Linting the shell script `install-binary.sh` with [shellcheck](https://github.com/koalaman/shellcheck), [shfmt](https://github.com/mvdan/sh) and [checkbashisms](https://linux.die.net/man/1/checkbashisms). Covered by https://github.com/luizm/action-sh-checker
To gain a preview of the flow, take a look here: …

Migrate to GH actions

---

Makefile
install-binary.sh

Cleanup of install-binary.sh and fix lint errors in the new github action job.

Fix lint errors in install-binary.sh

---

cmd/options.go
cmd/release.go
cmd/revision.go
cmd/rollback.go
cmd/upgrade.go
diff/diff.go
diff/diff_test.go

If we rename objects, they will appear as
add and remove actions, which makes it difficult
to assess the semantic delta, which may only be
a simple renaming.
The current implementation creates potentially
a diff between every add/remove item, which
means O(n^2) runtime. So it should only be
enabled if such changes are rare

feat: --find-renames for discovering renames based on content

---

.github/workflows/ci.yaml

I have added alpine as a install target in the test matrix.
Alpine also uses busybox, so not sure if it needed to add a separate busybox target or if this is enough.
Fixes #347

Add Alpine Linux target to CI

---

cmd/upgrade.go

Remove **generation** and **deployment.kubernetes.io/revision** from three-way-merge diff
Fixes #349

Remove generation and revision from three-way-merge diff

---

README.md
cmd/helm3.go
cmd/upgrade.go

Support for `--kube-version` was ported to Helm 3 on https://github.com/helm/helm/pull/9040.
I'm using `helm-diff` as a mechanism to determine if a PR will cause changes on installed releases. Then, depending on the result, I trigger pipelines dynamically targeting only the affected releases. Currently, not all the clusters share the same Kubernetes version, so being able to use this Helm 3 feature on Helm diff will improve a lot my workflow.

chore: Added support for setting --kube-version

---

diff/report.go
diff/report_test.go

The current regexp doesn't match all possible apis, for example
`cert-manager.io`.
As there is a closing `)` we can simply take everything before it.
Also resource names can have . in their name.

diff/report: fix key regexp

---

manifest/parse.go
manifest/parse_test.go
manifest/testdata/secret_immutable.yaml

This is useful for immutable secrets which are typically named as secret-base-name-<.data hash>. Previously old and new secrets were considere completely independent ConfigMap/Secret. With this annotation user can add "helm.sh/base-name: secret-base-name" annotation and compare old and new objects similar to git rename.
#378

Annotation to override object name for diff purposes

---

Makefile
scripts/release.sh

Golang image was missing bzip2 so github-release binary didn't install
and release docker didn't work.

Added bzip2 to build docker. Updated golang image and github-release.

---

README.md

README.md had a lot of trailing whitespace, as well as couple of typos.

chore: Remove trailing whitespace and fix some typos in README

---

cmd/upgrade.go

Check the error returned by genManifest function when three way merge is performed. This fixes the cases when chart produces incorrect manifest (for example a Deployment without image in initContainers):
```
...
initContainers:
- name: nginx-init
...
```
Currently manifest with an error is just being dropped from comparison and appears as being removed in the diff:
```
$ helm diff upgrade dummy . --three-way-merge
default, dummy, Deployment (apps) has been removed:
- apiVersion: apps/v1
- kind: Deployment
- metadata:
-   creationTimestamp: "2022-10-21T08:22:50Z"
-   labels:
-     app.kubernetes.io/instance: dummy
-     app.kubernetes.io/managed-by: Helm
...
```
Now with the fix it will display the proper error:
```
Error: unable to generate manifests: cannot patch "dummy" with kind …
```

Check the error returned by genManifest

---

cmd/root.go

Allow setting the output format via an environment variable

feature(output): add environment variable for diff output format

---

README.md
cmd/upgrade.go

This change proposes making the output context configurable via an environment variable `HELM_DIFF_OUTPUT_CONTEXT`. This is useful for me to shorten the diff output by default, for large chart releases.

Add env var for --context flag

---

README.md
cmd/helm3.go
cmd/upgrade.go

Implements #396
Add post-renderder-args flags to keep in sync with helm's post-renderer-args flag

Add post-renderer-args flag

---

manifest/parse.go

Just keep skipping empty documents
Fixes #409

fix(parser): don't always skip the first YAML document

---

Makefile
cmd/upgrade.go

Hooks manifests would have been already added when `--three-way-merge=true` (by `genManifest` function). Unless `--no-hooks=true` have been supplied as well - making them being skipped earlier as well.
This results into only one case when hooks manifests should be added separately: `--three-way-merge=false --no-hooks=false` (the current defaults).
With the current code however, when charts contain hooks and `--three-way-merge=true`, some confusing output is returned (esp. on empty diff). That's because hooks manifests are added twice: first inside `genManifest` function, and then again by appending results of `getHooks` function.
```console
$ helm diff upgrade my-release my-chart --values values.yaml --three-way-merge=true
2022/12/01 16:52:34 Error: Found duplicate key "my-ns, my-cm, …
```

Skip `helm get hooks` when `--three-way-merge=true`

---

README.md
cmd/revision.go

Fix typo lastest->latest in doc/usage

---

cmd/helm3.go
cmd/upgrade.go

I believe helm-diff should eventually support all the helm-template flags including connection-related ones, so that helm-diff can be used in place where helm-template or helm-upgrade-dry-run to provide diff/dry-run functionality to existing script/program/etc.
This adds support for --insecure-skip-tls which is used to disable server verification on chart download.

Add support for --insecure-skip-tls-verify

---

README.md

Hiya :wave:, finishing off what #421 started :D

docs(README): fix typo `upgarde` -> `upgrade`

---

cmd/options.go
diff/diff.go
diff/diff_test.go

This PR allow to suppress the diff report by using regex.
This option is more designed for power users and give them full control about the output.
There is a new diff option `--suppress-output-line-regex`  which can be applied multiple time.
If a line from the report matches the regex, the line gets removed from the report. If the diff entry has no deltas, the whole diffEntry (file) gets removed, except the headline `default, nginx, Deployment (apps) has changed:`
Since `--suppress-output-line-regex` applied only to the output of an diff, the behavior of `--detailed-exit-code` is not touch. If there are differences which are suppressed, the exit code remains still 2.
Feature in action:
<details>
<summary>helm diff upgrade prometheus-node-exporter …

feat: Allow suppress diff line output by regex

---

cmd/helm3.go

Helm PR https://github.com/helm/helm/pull/9426 enables support for executing lookups during dry run. This PR is to make use of this new support in helm-diff. Backwards compatibility for older versions of helm is maintained by checking the helm version before setting the flag
Addresses issue: https://github.com/databus23/helm-diff/issues/449

Use dry-run=server to enable lookups

---

cmd/helm3.go
cmd/upgrade.go

As helm has a support of `--set-json` (added at https://github.com/helm/helm/pull/10693), let's propagate it from the user input for consistency.
Fixes #494

Support --set-json

---

README.md
cmd/helm3.go
cmd/upgrade.go
cmd/upgrade_test.go
main_test.go

This intends to fix a potential security issue introduced via #458 before cutting the next helm-diff release.
Since #458 (unreleased), we had forced helm-diff to use `helm template --dry-run=server` for Helm 3.13 or greater.
I think this can create an unintended security hole, where any users, who can run helm-diff via CI or any automation with an arbitrary chart and values, is able to view cluster resources via helm template's `lookup` functions.
Previously this was impossible because `helm template` run by `helm diff` had no access to the `lookup` function. To fix this, we need to make `--dry-run=server` optional. And we do so by changing helm-diff's `--dry-run` flag to accept only only booleans but also `client` and `server`. The updated flag usage is …

fix: Make dry-run=server optional

---

README.md
cmd/options.go

As also mentioned in the issue below, the current `--suppress` option only handles kind, but the vague description is causing confusion.
ref: https://github.com/databus23/helm-diff/issues/163
I think #468 is the fundamental solution, but first I would like to clarify the current specifications.

Fix description of diff suppress option

---

.github/workflows/release.yaml
.goreleaser.yml

To publish a release, we currently have to run `make docker-run-release` locally after tagging a release, which is not a huge effort but a bit cumbersome because we do it only a few times a year and that is long enough to lose my memory :)
Starting this change, we use a GHA workflow and goreleaser to automatically build and publish binaries whenever a new semver tag is created, so that we do not need to run `make` anymore.
I crafted the goreleaser configuration so that it produces the same archives that we use and helm-diff's install.sh relies on.
For example, the produced archives has contents like the below:
- plugin.yaml
- README.md
- LICENSE
- bin/diff
`bin/diff` is especially important because that's the path we use in the plugin.yaml.
You can test this almost locally, by running …

Automate releases using GHA

---

plugin.yaml

Once we merge this and cut a new v3.9.0 tag on GH web UI, #517 will automatically build and release binaries.

Bump plugin version to 3.9.0

---

cmd/upgrade.go

```
+args after legacy dry-run parsing: [--allow-unreleased manifests /tmp/chartify3644874502/helmfile-tests/manifests --reset-values]
********************
Release was not present in Helm.  Diff will show entire contents as new.
FAIL: "helmfile diff" should be consistent
```
/cc @mumoshu

fix: remove debug msg in normal mode

---

.github/dependabot.yml
.github/workflows/ci.yaml
.github/workflows/cleanup.yaml
.github/workflows/lint-sh.yaml
.github/workflows/lint.yaml

- Added dependabot config for actions and go modules
- Update all actions to latest versions
- Move `shell-lint` job to separate workflow file with path filtered triggers
- Setup go version from `go.mod` file (caching is enabled by default)
- Add workflow to delete PR cache

chore: Update github actions

---

plugin.yaml

Missed bumping it when we released 3.9.1 🤦
We've already cut 3.9.1 so this prepares the next release, which might contain dep updates only.

Bump plugin version to 3.9.2

---

cmd/upgrade.go
cmd/upgrade_test.go
go.mod

This is a follow-up on #499 which redoes it without relying on cobra's DisableFlagParsing. DisableFlagParsing turned out to break far many things than I imagined!
Fixes #536
Ref #537 #538

Remake dry-run=server optional

---

cmd/root.go
cmd/upgrade.go

I installed helm diff today and stumbled across these few occurrences of slightly incorrect wording "used visualize" in the help output.
Let me know if this is useful or needs any adjustments. Thanks for your work!

Improve wording in help

---

.golangci.yaml
cmd/helm3.go
go.mod
go.sum

Use github.com/Masterminds/semver/v3 instead of github.com/Masterminds/semver

deps: use semver/v3 instead of semver

---

cmd/helm3.go
cmd/upgrade.go

Hi all,
this PR enables support for `--set-literal`, see https://github.com/helm/helm/pull/9182 and issue #474 here.

Implement support for pass-through of --set-literal flag/values

---

.golangci.yaml
cmd/helm3.go
cmd/helpers.go
cmd/upgrade.go
main.go
manifest/parse.go

[Errorlint](https://github.com/polyfloyd/go-errorlint) help follow best practices concerning errors

enable errorlint linter

---

diff/diff.go
diff/diff_test.go
manifest/parse.go

The annotation `helm.sh/resource-policy: keep` instructs Helm to skip deleting this resource when a Helm operation would result in its deletion. As the resource is not actually deleted, exclude it from the generated diff.

Add support for resource-policy: keep (#246)

---

install-binary.sh

This isn't a real test, and it produces noise on each install, which isn't desired in case of running under CI environment.
Fixes https://github.com/databus23/helm-diff/issues/605.

Don't output help on install

---

README.md

add `--output=dyff` to possible values to README.md

---

go.mod

Updated the Go toolchain version from 1.22.2 to 1.22.4 in go.mod to ensure compatibility with the latest security patches.

chore(deps): update Go toolchain version to 1.22.4 for CVE-2024-24790

---

.github/workflows/ci.yaml
.github/workflows/lint.yaml
.golangci.yaml
diff/diff.go
diff/report.go
go.mod
main_test.go

This pull request includes several updates to the CI and lint workflows, as well as a version upgrade in the `go.mod` file. The most important changes are the updates to the Helm and GolangCI versions, and the Go version in `go.mod`.
* [`.github/workflows/ci.yaml`](diffhunk://#diff-944291df2c9c06359d37cc8833d182d705c9e8c3108e7cfe132d61a06e9133ddL46-R46): Updated Helm version from `v3.16.1` to `v3.16.2` across multiple job configurations. [[1]](diffhunk://#diff-944291df2c9c06359d37cc8833d182d705c9e8c3108e7cfe132d61a06e9133ddL46-R46) [[2]](diffhunk://#diff-944291df2c9c06359d37cc8833d182d705c9e8c3108e7cfe132d61a06e9133ddL64-R73) [[3]](diffhunk://#diff-944291df2c9c06359d37cc8833d182d705c9e8c3108e7cfe132d61a06e9133ddL114-R114)
* [`.github/workflows/lint.yaml`](diffhunk://#diff-4b122024a3a28ded6 …

feat(ci): update helm and go version in ci workflow

---

README.md
cmd/helm3.go
cmd/upgrade.go

Since this flag was added to Helm it has made life much easier when upgrading charts with multiple values files. By force of habit I run `helm diff upgrade` before nearly every `helm upgrade`, so it's a bummer when this flag isn't recognized. This PR adds support for it and closes #571.
PS. I'm very new to Go, and it probably shows in the effort. I'd appreciate any pointers to improve the code, or any suggestions in general. Thanks!

Support the upgrade flag --reset-then-reuse-values added in Helm v3.14.0

---

README.md
cmd/helm3.go
cmd/upgrade.go

https://github.com/helm/helm/pull/12743 Helm 3.16.0!
This pull request introduces a new option to skip schema validation when rendering templates in Helm 3. The key changes include adding a new flag and updating the relevant command structures and functions to support this new option.
New feature addition:
* [`cmd/helm3.go`](diffhunk://#diff-a0408f7d6a173149c3bcc5a85ae0fd7908f9baf448a1678fa755688373682fceR201-R204): Added support for the `--skip-schema-validation` flag in the `template` function to allow users to skip validation of rendered manifests against the Kubernetes OpenAPI schema.
Command structure updates:
* [`cmd/upgrade.go`](diffhunk://#diff-6b91a7cb88f6ad245b3fa4bc01b4789e1a23b940920626a6cffbffc0317ba2cfR50): Added a new field `SkipSchemaValidation` to the `diffCmd` struct to …

feat: add skip-schema-validation feature

---

.github/workflows/ci.yaml

This pull request includes a small change to the `.github/workflows/ci.yaml` file. The change removes the `version` specification for the `engineerd/setup-kind` action, which previously was set to `v0.11.1`.

refactor(ci): remove redundant kind version in ci.yaml

---

.github/workflows/ci.yaml
go.mod
go.sum

This pull request includes updates to the Helm and kubectl versions in the CI workflow and the `go.mod` file to ensure compatibility and leverage the latest features and fixes.
Changes to CI workflow:
* Updated Helm version from `v3.16.2` to `v3.16.4` in the CI workflow matrix to ensure the latest fixes and improvements are included. (.github/workflows/ci.yaml) [[1]](diffhunk://#diff-944291df2c9c06359d37cc8833d182d705c9e8c3108e7cfe132d61a06e9133ddL46-R46) [[2]](diffhunk://#diff-944291df2c9c06359d37cc8833d182d705c9e8c3108e7cfe132d61a06e9133ddL64-R73) [[3]](diffhunk://#diff-944291df2c9c06359d37cc8833d182d705c9e8c3108e7cfe132d61a06e9133ddL114-R114)
Changes to dependencies:
* Updated Helm version from `v3.16.3` to `v3.16.4` in the `go.mod` file to maintain consistency with the CI workflow. …

build: update Helm to v3.16.4 and kubectl to v0.31.3

---

plugin.yaml

This pull request includes a small change to the `plugin.yaml` file. The change updates the version of the Helm plugin from `3.9.12` to `3.9.13` to reflect the latest build.

Bump helm-diff version to 3.9.13

---

plugin.yaml

This pull request includes a minor version update for the `plugin.yaml` file. The version number has been incremented from "3.9.13" to "3.9.14".
Changes in `plugin.yaml`:
* Updated version from "3.9.13" to "3.9.14".

Bump helm-diff version to 3.9.14

---

.gitignore
cmd/helpers.go
cmd/release.go
cmd/revision.go
cmd/rollback.go
cmd/upgrade.go
manifest/generate.go

This PR moves manifests generate related code from the `cmd` package to the `manifest` and make Generate manifests function public. 
fixes #717

Able to use project components as golang library

---

plugin.yaml

This pull request includes a version update for the `diff` plugin in the `plugin.yaml` file. The version has been updated from `3.9.14` to `3.10.0` to reflect the latest changes.
* [`plugin.yaml`](diffhunk://#diff-d55bf51ed4d80c9c0eef853d64823da5d91fad2e860465f50b40c355fd307afaL4-R4): Updated the version from `3.9.14` to `3.10.0`.

Bump helm-diff version to 3.10.0

---

.github/workflows/lint.yaml
go.mod

This pull request includes updates to the Go version and the golangci-lint version used in the project.
Version updates:
* [`.github/workflows/lint.yaml`](diffhunk://#diff-4b122024a3a28ded65da76a2f1bface1f3a27328374438d1298d25585fe0603bL24-R24): Updated the `golangci-lint` action version from `v1.61.0` to `v1.64.5`.
* [`go.mod`](diffhunk://#diff-33ef32bf6c23acb95f5902d7097b7a1d5128ca061167ec0716715b0b9eeaa5f6L3-R3): Updated the Go version from `1.23.2` to `1.24`.

build: update golang version to 1.24 and lint to v1.64.5

---

cmd/helm3.go
cmd/upgrade.go
diff/diff.go
diff/diff_test.go
diff/report.go
manifest/generate.go
manifest/parse.go
manifest/parse_test.go
manifest/testdata/pod_no_release_annotations.yaml
manifest/testdata/pod_release_annotations.yaml
manifest/util.go
manifest/util_test.go

I trying to add support of the new `--take-ownership` argument that appears in Helm 3.17.
This works by trying to match manifests of the release with existing ones on the cluster. If the release mismatch, then the changing of ownership is displayed in the report.
I have not a lot experience in Go, nor on this project.
Fix #731

Add support for --take-ownership parameter

---

manifest/util_test.go

This pull request includes a small change to the `manifest/util_test.go` file. The change modifies the test assertion method used in the `Test_deleteStatusAndTidyMetadata` function to improve consistency and readability.
* [`manifest/util_test.go`](diffhunk://#diff-e9df6be45179cffae75a84c75b097fc5fac0b58b43bbdae3300603d0b7631851L94-R94): Changed `require.EqualValuesf` to `require.Equalf` in the `Test_deleteStatusAndTidyMetadata` function.

test: Optimize deleteStatusAndTidyMetadata test assertion

---

README.md
cmd/helm3.go
cmd/upgrade.go

This PR allows usage of `helm template` flag `--include-crds` during a `helm diff upgrade`.
When using `helmfile` with `helm diff upgrade` command you have to use post-renderer to get the fully rendered manifest and allow rendering of all resources including CRDs that are deployed via a sub-chart i.e. kyverno.
In order to be able to move a way from post-renderer and use `kustomization` builtin support of `helmfile` without breaking the manifest that you can get via `helm get manifest -n namespace release` it is needed to allow rendering the included crds if the chart decided to render these via a dependency.
It also makes `three-way-merge` more usefull as you now also get the diff for included crd changes.
Merging this PR into an upcoming release would allow anyone to be able to catch …

Allow diff to include crds

---

diff/diff.go
diff/diff_test.go
diff/report.go

If a diff exists but is suppressed in the output change the text to make it more clear what is actually happening.

feat: change output if all diff output is suppressed

---

plugin.yaml

This pull request updates the version of the Helm plugin in the `plugin.yaml` file.
* [`plugin.yaml`](diffhunk://#diff-d55bf51ed4d80c9c0eef853d64823da5d91fad2e860465f50b40c355fd307afaL4-R4): Updated the `version` field from `3.11.0` to `3.12.0` to reflect the new plugin version.

Bump helm-diff version to 3.12.0

---

diff/diff.go
diff/diff_test.go

This pull request refactors the handling of secrets in the `diff` package to improve code reuse and readability. The changes include introducing a helper function for decoding secrets, updating related methods to use this helper, and adding a new test case to ensure correct behavior when both `stringData` and `data` fields are present in Kubernetes secrets.
* Introduced a new helper function `preHandleSecrets` in `diff/diff.go` to centralize the logic for decoding secrets and handling errors. This function is now used in both `redactSecrets` and `decodeSecrets` to avoid code duplication. [[1]](diffhunk://#diff-9b5d2fa5162a9c23e7b0c96446b28d54aa4c6676a697d2eb26073a5a76db602fL242-L251) [[2]](diffhunk://#diff-9b5d2fa5162a9c23e7b0c96446b28d54aa4c6676a697d2eb26073a5a76db602fR275-R285) …

refactor(diff): extract secret handling to preHandleSecrets

---

Makefile

This pull request updates the `Makefile` to align with Helm's newer environment variable conventions by replacing the deprecated `HELM_HOME` with `HELM_DATA_HOME`. The changes ensure compatibility with Helm 3 and improve maintainability.
* Replaced `HELM_HOME` with `HELM_DATA_HOME` in the `Makefile` to use the newer Helm environment variable for plugin data storage.
* Updated the `install` target to reflect the change from `HELM_HOME` to `HELM_DATA_HOME` for creating directories and copying files during plugin installation.

refactor(Makefile): use HELM_DATA_HOME instead of HELM_HOME

---

Makefile

This pull request updates the `Makefile` to standardize the use of the `HELM_HOME` variable instead of `HELM_DATA_HOME` for consistency in Helm environment configuration.
* [`Makefile`](diffhunk://#diff-76ed074a9305c04054cdebb9e9aad2d818052b07091de1f20cad0bbac34ffb52L1-R1): Replaced `HELM_DATA_HOME` with `HELM_HOME` throughout the file to align with Helm's environment variable naming conventions. This includes updates in the variable definition and the `install` target commands. [[1]](diffhunk://#diff-76ed074a9305c04054cdebb9e9aad2d818052b07091de1f20cad0bbac34ffb52L1-R1) [[2]](diffhunk://#diff-76ed074a9305c04054cdebb9e9aad2d818052b07091de1f20cad0bbac34ffb52L18-R20)

refactor(Makefile): Replace HELM_DATA_HOME with HELM_HOME

---

CONTRIBUTING.md
cmd/upgrade.go

Messages that help the reader make sense of the output are printed to stdout and not to stderr right now. When using the structured output options (such as `--output json`), this causes the output to not be valid JSON. It requires the user to filter out the non-JSON lines from the output and then pipe the output to programs that expect valid JSON input (such as [`jq`])
We are using the Helm diff plugin when deploying to our production environments, and we need to [filter] these lines out from the output. The logic that we have implemented is fragile and we would have to keep it in sync with changes in the Helm Diff plugin itself.
A better way to do this would be to print the messages for the reader to standard error, and keep the standard output purely output that can be piped into …

Print error messages to stderr, not stdout

---

plugin.yaml

This pull request includes a minor version update to the `plugin.yaml` file. The change updates the plugin's version from `3.12.0` to `3.12.1`, reflecting a new build.

Bump helm-diff version to 3.12.1

---

plugin.yaml

This pull request updates the version of the Helm plugin in the `plugin.yaml` file to reflect the latest release.
Version update:
* [`plugin.yaml`](diffhunk://#diff-d55bf51ed4d80c9c0eef853d64823da5d91fad2e860465f50b40c355fd307afaL4-R4): Updated the `version` field from "3.12.1" to "3.12.2" to indicate the new version of the plugin.

chore: update plugin version to 3.12.2

---

.github/workflows/ci.yaml
go.mod

This pull request includes updates to dependencies and configuration files to ensure compatibility and maintain up-to-date versions. The most important changes involve updating the Helm version used in CI workflows and bumping the Go version in the `go.mod` file.
* [`.github/workflows/ci.yaml`](diffhunk://#diff-944291df2c9c06359d37cc8833d182d705c9e8c3108e7cfe132d61a06e9133ddL46-R46): Updated the Helm version from `v3.17.3` to `v3.17.4` across all relevant configurations, including the matrix and specific job definitions. [[1]](diffhunk://#diff-944291df2c9c06359d37cc8833d182d705c9e8c3108e7cfe132d61a06e9133ddL46-R46) [[2]](diffhunk://#diff-944291df2c9c06359d37cc8833d182d705c9e8c3108e7cfe132d61a06e9133ddL64-R73) [[3]](diffhunk://#diff-944291df2c9c06359d37cc8833d182d705c9e8c3108e7cfe132d61a06e …

build: update Helm version to v3.17.4 and Go to 1.24.5

---

plugin.yaml

This pull request updates the version of the `diff` plugin in the `plugin.yaml` file.
* Plugin version updated from "3.12.4" to "3.12.5" in `plugin.yaml`.

build: update plugin version to 3.12.5

---

.github/workflows/ci.yaml
install-binary.ps1
plugin.yaml

This pull request introduces significant updates to the installation process and configuration for the Helm Diff plugin, particularly adding support for Windows.
fix: https://github.com/databus23/helm-diff/issues/316
* Added a new PowerShell script `install-binary.ps1` to handle the installation process on Windows. This script includes functions for determining system architecture, fetching the appropriate plugin version, creating a temporary directory, constructing the download URL, downloading the plugin, and installing it.
* Updated `plugin.yaml` to support platform-specific commands and hooks. This includes specifying different commands and hooks for Windows and other operating systems, ensuring compatibility across platforms.

refactor(plugin.yaml): enhance platform support and update commands
